### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Naddiseo**
Added the steps in salphaseion that have been made available so far

### CODE REVIEW

**Review by jamiegreen7 — COMMENTED** [review]
Approve

**Comment by jamiegreen7** [comment]
> Approve

**Review by jamiegreen7 — COMMENTED** [review]
Approve

**Comment by jamiegreen7** [comment]
> Added the steps in salphaseion that have been made available so far

**Comment by danishalich07-arch** [comment]
Hey sir give me key

**Comment by danishalich07-arch** [comment]
+923250483826

**Pull request merged**
